services:
  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8000:8000"
    volumes:
      - ./user_service/users.db:/app/users.db
    environment:
      - DATABASE_FILE_NAME=sqlite:////app/users.db
    restart: unless-stopped
  
  posts_service:
    build: ./posts_service
    container_name: posts_service
    ports:
      - "50052:50051"
    volumes:
      - ./posts_service/posts.db:/app/posts.db
    environment:
      - DATABASE_FILE_NAME=sqlite:////app/posts.db
    restart: unless-stopped

  stats_service:
    build: ./stats_service
    container_name: stats_service
    ports:
      - "50053:50051"
    volumes:
      - ./user_service/users.db:/app/users.db:ro
      - ./posts_service/posts.db:/app/posts.db:ro
    restart: unless-stopped

  gateway_service:
    build: ./gateway_service
    container_name: gateway_service
    ports:
      - "8080:8000"
    environment:
      - USER_SERVICE_URL=http://user_service:8000
    restart: unless-stopped

  user_service_tests:
    build:
      context: ./user_service
      dockerfile: Dockerfile.test
    container_name: user_service_tests
    command: pytest -vv -s --maxfail=1 --disable-warnings -q
    volumes:
      - ./user_service/users.db:/app/users.db
    environment:
      - DATABASE_FILE_NAME=sqlite:////app/users.db
  
  posts_service_tests:
    build:
      context: ./posts_service
      dockerfile: Dockerfile.test
    container_name: posts_service_tests
    command: pytest -vv -s --maxfail=1 --disable-warnings -q
    volumes:
      - ./posts_service/posts.db:/app/posts.db
    environment:
      - DATABASE_FILE_NAME=sqlite:////app/posts.db
  
  gateway_service_tests:
    build:
      context: ./gateway_service
      dockerfile: Dockerfile.test
    container_name: gateway_service_tests
    command: pytest -vv -s --maxfail=1 --disable-warnings -q

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped
  
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
