FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir pytest

COPY . .

CMD ["pytest", "--maxfail=1", "--disable-warnings", "-q"]
