# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stats_pb2 as stats__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stats_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPostStats = channel.unary_unary(
                '/statsservice.StatsService/GetPostStats',
                request_serializer=stats__pb2.GetPostStatsRequest.SerializeToString,
                response_deserializer=stats__pb2.GetPostStatsResponse.FromString,
                _registered_method=True)
        self.GetPostViewDynamics = channel.unary_unary(
                '/statsservice.StatsService/GetPostViewDynamics',
                request_serializer=stats__pb2.GetPostViewDynamicsRequest.SerializeToString,
                response_deserializer=stats__pb2.GetPostViewDynamicsResponse.FromString,
                _registered_method=True)
        self.GetPostLikeDynamics = channel.unary_unary(
                '/statsservice.StatsService/GetPostLikeDynamics',
                request_serializer=stats__pb2.GetPostLikeDynamicsRequest.SerializeToString,
                response_deserializer=stats__pb2.GetPostLikeDynamicsResponse.FromString,
                _registered_method=True)
        self.GetPostCommentDynamics = channel.unary_unary(
                '/statsservice.StatsService/GetPostCommentDynamics',
                request_serializer=stats__pb2.GetPostCommentDynamicsRequest.SerializeToString,
                response_deserializer=stats__pb2.GetPostCommentDynamicsResponse.FromString,
                _registered_method=True)
        self.GetTopPosts = channel.unary_unary(
                '/statsservice.StatsService/GetTopPosts',
                request_serializer=stats__pb2.GetTopPostsRequest.SerializeToString,
                response_deserializer=stats__pb2.GetTopPostsResponse.FromString,
                _registered_method=True)
        self.GetTopUsers = channel.unary_unary(
                '/statsservice.StatsService/GetTopUsers',
                request_serializer=stats__pb2.GetTopUsersRequest.SerializeToString,
                response_deserializer=stats__pb2.GetTopUsersResponse.FromString,
                _registered_method=True)


class StatsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPostStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostViewDynamics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostLikeDynamics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostCommentDynamics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPostStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostStats,
                    request_deserializer=stats__pb2.GetPostStatsRequest.FromString,
                    response_serializer=stats__pb2.GetPostStatsResponse.SerializeToString,
            ),
            'GetPostViewDynamics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostViewDynamics,
                    request_deserializer=stats__pb2.GetPostViewDynamicsRequest.FromString,
                    response_serializer=stats__pb2.GetPostViewDynamicsResponse.SerializeToString,
            ),
            'GetPostLikeDynamics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostLikeDynamics,
                    request_deserializer=stats__pb2.GetPostLikeDynamicsRequest.FromString,
                    response_serializer=stats__pb2.GetPostLikeDynamicsResponse.SerializeToString,
            ),
            'GetPostCommentDynamics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostCommentDynamics,
                    request_deserializer=stats__pb2.GetPostCommentDynamicsRequest.FromString,
                    response_serializer=stats__pb2.GetPostCommentDynamicsResponse.SerializeToString,
            ),
            'GetTopPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopPosts,
                    request_deserializer=stats__pb2.GetTopPostsRequest.FromString,
                    response_serializer=stats__pb2.GetTopPostsResponse.SerializeToString,
            ),
            'GetTopUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopUsers,
                    request_deserializer=stats__pb2.GetTopUsersRequest.FromString,
                    response_serializer=stats__pb2.GetTopUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'statsservice.StatsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('statsservice.StatsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPostStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statsservice.StatsService/GetPostStats',
            stats__pb2.GetPostStatsRequest.SerializeToString,
            stats__pb2.GetPostStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostViewDynamics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statsservice.StatsService/GetPostViewDynamics',
            stats__pb2.GetPostViewDynamicsRequest.SerializeToString,
            stats__pb2.GetPostViewDynamicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostLikeDynamics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statsservice.StatsService/GetPostLikeDynamics',
            stats__pb2.GetPostLikeDynamicsRequest.SerializeToString,
            stats__pb2.GetPostLikeDynamicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostCommentDynamics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statsservice.StatsService/GetPostCommentDynamics',
            stats__pb2.GetPostCommentDynamicsRequest.SerializeToString,
            stats__pb2.GetPostCommentDynamicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statsservice.StatsService/GetTopPosts',
            stats__pb2.GetTopPostsRequest.SerializeToString,
            stats__pb2.GetTopPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statsservice.StatsService/GetTopUsers',
            stats__pb2.GetTopUsersRequest.SerializeToString,
            stats__pb2.GetTopUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
